services:
  app:
    platform: linux/amd64
    build: .
    command: functions-framework-python --target execute --debug
    ports:
      - 8080:8080
    volumes:
      - .:/app
    env_file:
      - .env
    tty: true
