version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-20210929
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  app:
    build: .
    command: sh -c "/bin/bash"
    env_file: .env
    volumes:
      - .:/app
    tty: true
